added units explanation
Roboy/myo_blink pull request #8
Opened 2017-05-08 15:22 UTC by missxa

2017-05-08 18:20 UTC, compiaffe requested changes

2017-05-08 18:20 UTC, compiaffe commented on README.md
> +- 1 rad ~ 18000 ticks
How do you get to this number?

It is depended on 
- the encoder (512 encoder tics/rotation in our case)
- the gear box (53:1) - see https://roboy.open-aligni.com/part/show/359?revision_id=316#
-----------
512*53 = 27136 tics per rotation of the tendon reel

27136 tics/rotation = 27136tics/2*pi RAD = 4318.955912781

2017-05-08 18:20 UTC, compiaffe commented on README.md
> +- actuarorPosition and tendonDisplacement are displayed in encoder ticks
actuatorPosition (typo)

2017-05-08 18:25 UTC, missxa commented on README.md
> +- 1 rad ~ 18000 ticks
from the yaml file: rad_per_encoder_count: 0.00005788606746738269
ticks per rad = 1/ 0.00005788606746738269 ~ 18000

2017-05-08 18:25 UTC, missxa commented on README.md
> +- 1 rad ~ 18000 ticks
no?

2017-05-08 18:53 UTC, compiaffe commented on README.md
> +- 1 rad ~ 18000 ticks
hmm, are you sure?
encoder and gear box values are certainly correct.

How many tics do you get when doing a full rotation (visually verified)

2017-05-08 20:48 UTC, compiaffe commented on README.md
> +- 1 rad ~ 18000 ticks
Ahh, found what it was deep in the back of my mind:

- Gear box is correct at 53:1
- Encoder tics is also correct at 512 tics per rotation, BUT being a quadrature encoder a tic is actually 4 tics/pulses:

512*53*4=108544 tics per rotation 

108544/(2+3.1415) = 17275.8236 or ~18000

2017-05-09 05:38 UTC, compiaffe approved these changes

2017-05-09 14:49 UTC, merged